export const THEMES = [
  "terracotta",
  "midnight_blue",
  "forest",
  "ocean",
  "blueprint",
  "noir",
  "sunset",
  "emerald",
  "autumn",
  "pastel_dream",
  "neon_cyberpunk",
  "japanese_ink",
  "monochrome_blue",
  "warm_beige",
  "copper_patina",
  "gradient_roads",
  "contrast_zones",
];

export const THEME_LABELS: Record<string, string> = {
  terracotta: "Terracotta",
  midnight_blue: "Midnight Blue",
  forest: "Forest",
  ocean: "Ocean",
  blueprint: "Blueprint",
  noir: "Noir",
  sunset: "Sunset",
  emerald: "Emerald",
  autumn: "Autumn",
  pastel_dream: "Pastel Dream",
  neon_cyberpunk: "Neon Cyberpunk",
  japanese_ink: "Japanese Ink",
  monochrome_blue: "Monochrome Blue",
  warm_beige: "Warm Beige",
  copper_patina: "Copper Patina",
  gradient_roads: "Gradient Roads",
  contrast_zones: "Contrast Zones",
};
